name: Ruby Gem

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Ruby 3.3.5
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.3.5
    
    - name: Install dependencies
      run: bundle install
    
    - name: Run tests
      run: bundle exec rake test
    
    - name: Build gem
      run: gem build *.gemspec
    
    - name: Publish to GitHub Packages
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:github: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem push *.gem
      env:
        GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_AUTH_TOKEN }}
